stages:
  data_ingestion:
    cmd: python src/palmTreesCounter/pipeline/stage_01_data_ingestion.py
    deps:
      - src/palmTreesCounter/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/Palm-Counting-349images
